name: Build LaTeX document

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: false
          latexmk_shell_escape: true

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf

      - name: Move compiled PDF to folder
        run: |
          mkdir -p compiled_pdfs
          mv main.pdf compiled_pdfs/main.pdf
          
      - name: Commit compiled PDF back to repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add compiled PDF"
          add: "compiled_pdfs/main.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
