name: Build LaTeX document

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find main .tex file
        id: findtex
        run: |
          # Find the first .tex file in the repo
          TEX_FILE=$(find . -name "*.tex" | head -n 1)
          echo "Found TeX file: $TEX_FILE"
          echo "texfile=$TEX_FILE" >> $GITHUB_OUTPUT
          PDF_NAME=$(basename "$TEX_FILE" .tex).pdf
          echo "pdfname=$PDF_NAME" >> $GITHUB_OUTPUT

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ steps.findtex.outputs.texfile }}
          latexmk_use_lualatex: false
          latexmk_shell_escape: true

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: ${{ steps.findtex.outputs.pdfname }}

      - name: Move compiled PDF to folder
        run: |
          mkdir -p Paper_pdf
          mv "${{ steps.findtex.outputs.pdfname }}" Paper_pdf/

      - name: Commit compiled PDF back to repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add compiled PDF"
          add: "Paper_pdf/${{ steps.findtex.outputs.pdfname }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
