name: Build LaTeX document

on:
  push:
    paths:
      - '**.tex'
      - '**.bib'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: false
          latexmk_shell_escape: true
          latexmk_args: '-jobname="Low Power Scheduling for High-Level Synthesis"'

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: "Low Power Scheduling for High-Level Synthesis.pdf"

      - name: Move compiled PDF to folder
        run: |
          mkdir -p Paper_pdf
          mv "Low Power Scheduling for High-Level Synthesis.pdf" Paper_pdf/

      - name: Commit compiled PDF back to repository
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add compiled PDF"
          add: "compiled_pdfs/Low Power Scheduling for High-Level Synthesis.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
